name: Deploy to Staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP_DEL_SERVIDOR }}
          username: ${{ secrets.USUARIO_SERVIDOR }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/lemp-sites/santiago_capellino/staging
            git pull origin develop